### ISSUE TITLE
設定客製抬頭會與設定不符

### ISSUE THREAD

**Issue by 0oWoodenDooro0** [ntut-open-source-club/practical-tools-for-simple-design#187] opened 2024-05-03 03:57 UTC
### Problem

![Screenshot 2024-05-03 115425](https://github.com/ntut-open-source-club/practical-tools-for-simple-design/assets/58562009/916169fc-ef49-4cbf-9ea5-db7b0a96f583)
會與config.json不一樣 會有亂碼

### Steps to reproduce

0

### Expected behavior

0

### PTSD version

commit b55fbeb4

### Operating system/version

win11

### CMake version

unknown

### CMakeCache.txt

[CMakeCache.txt](https://github.com/ntut-open-source-club/practical-tools-for-simple-design/files/15196064/CMakeCache.txt)

### OpenGL Info

```txt
[info] OpenGL Info
 [info]   Vendor: NVIDIA Corporation
 [info]   Renderer: NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2
 [info]   Version: 4.1.0 NVIDIA 552.22
 [info]   GLSL Version: 4.10 NVIDIA via Cg compiler
```

**Comment by Dragonfly911117** [comment] 2024-05-05 01:27
This is caused by the `string_view PTSD_Config::TITLE` pointing to bad address. Will be fixed in days.

**Closed** 2024-05-23 05:25 UTC
Labels: bug
